### ISSUE TITLE
how can I run it on http

### ISSUE THREAD

**Issue by berTrAM888** [mcpa-stlouis/hack-the-arch#35]
how can I run it on http?

**Comment by veryredheaded** [comment]
I'm also struggling with accessing the app inside a browser. 
I tried to access the IP of my docker machine, as described in https://github.com/mcpa-stlouis/hack-the-arch/blob/dev/DOCKER_README.md, but this doesn't seem to work...

Can someone provide clearer/more precise instructions for this? Thank you in advance!

**Comment by paullj1** [comment]
So pardon my stupid question, but how are you running Docker? The compose
file will map the ports you need to the host running the Docker engine.
Docker machine != Docker container. If you’re running the engine natively,
then you can browse to localhost.

Does that make sense?

**Comment by paullj1** [comment]
To answer the original question, running HTA over http is not recommended/supported since passwords are transmitted.  Https, is the recommended way, and if you start puma the way the compose file is written, then you should have no problem.

**Comment by veryredheaded** [comment]
@paullj1 Thank you for answering. I'm sorry, but I've read your instructions numerous times now, and still can't help but feeling that there are some guidelines missing. _Important to note here:_ I'm not a pro, so my issues might not seem reasonable or worthwhile to you. Nevertheless, I would really like to successfully configure and test your platform. So, here is what I (didn't) understand following your [Getting Started](https://github.com/mcpa-stlouis/hack-the-arch) section: 

- There are no requirements regarding the OS, so I atempted an installation on a **64-bit Ubuntu 16.04.3 Desktop**
- Installed Ruby 2.3.1 (as defined in the [Requirements](https://github.com/mcpa-stlouis/hack-the-arch) section
- Cloned the current state of the master branch
- You updated your Gemfile (requires Ruby 2.3.3 now) but not the instructions... So I installed **Ruby 2.3.3** to avoid compatibility issues
- What is meant by: 
> This app is presently designed to be deployed in a heroku environment 

?
- Do I need to have an existing (newly created, empty) Heroku app, and deploy this repo to my app? Is the address of this app the one to be set for the HOST environment variable? These may seem like really dumb questions, but I don't really understand...
- When do I have to run `bundle exec rake db:seed` ? Are there other commands necessary to get this thing running? What are the credentials `admin@gmail.com : password` for?
- How is the app actually started? How do I access it?

It would be nice to have more detailed instructions on the initial configuration process. Maybe not every single command but at least a full (up-to-date) list of requirements and a list of necessary steps.

Thanks in advance!

**Comment by paullj1** [comment]
@veryredheaded, I'll do my best to answer some of your questions.  Before I start though, it might be worth mentioning that my instructions do assume a bit of background in rails development.  In other words, I assumed that anyone who might be trying to deploy a  rails web app would have some experience doing so.  That said, the reason I created the docker container and deployment option was for those without that experience.  I'd strongly suggest pursuing that option though you might have to checkout the [dev](https://github.com/mcpa-stlouis/hack-the-arch/tree/dev) branch and follow the DOCKER_README instructions.

* There are no OS requirements because rails is a cross platform web app platform.  As long as you can install rails, the app should run (again, assuming you understand rails)
* Please visit [heroku.com](heroku.com).  It's an IaaS provider.
* The HOST env variable is independent of heroku.  It's how the automated e-mails know where to direct users when they sign up.  So this should be the where the app is hosted.
* Seeding the database is done after deploying the app, but before using it.  Again, basic understanding of rails and web app development is useful here.  This will create the admin user in the db with those credentials.  You can then use those credentials to log into HTA.
* Again, basic understanding of a rails app or web app development in general is extremely useful here.  Your app can be started many ways, but essentially, it's a collection of ruby packages that handle requests (by default on port 3000 on the global listener).  The app can generally be started by running `bundle exec rails server`.  That, by default, will launch the app in dev mode and is not recommended for production use.  For more advanced production deployments... again, please read about rails apps.

I'm sorry that probably wasn't the step-by-step directions you were looking for.  My base level assumption when writing this app was basic understanding of the rails platform. That said, if you are interested in learning rails, there's a fantastic guide for free on the internet here: [http://railstutorial.org/](http://railstutorial.org/).  Otherwise, please use the docker deployment option. 

I hope this helps.

**Comment by veryredheaded** [comment]
@paullj1 thank you so much for the detailed answer. I will definitely look into rails apps for better understanding.

Since I have no experience with it, I _have_ tried the docker option first, but didn't know how to actually access HTA via browser. That was my main problem. But I will try to do it again, with the dev branch this time...

Thanks for your efforts and sorry for all the stupid questions :/

**Comment by paullj1** [comment]
Accessing it will be your docker host's IP (depends on how you're running
the docker engine).  If you're running it in an Ubuntu VM natively, you
should be able to access it at: https://UBUNTU_VM_IP/

**Comment by veryredheaded** [comment]
@paullj1 Thank you so much! It finally works :) 

![hta_screenshot](https://user-images.githubusercontent.com/18488581/33128680-8a24f9e8-cf8d-11e7-8b94-8d65ac9355a9.png)

**Comment by paullj1** [comment]
Great to hear!
